//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workie.DeployHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workie.DeployHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workie Deploy Helper Program.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose remote host to deploy Workie.Web.Admin.
        /// </summary>
        internal static string ChooseRemoteHostToDeployWorkieWebAdmin {
            get {
                return ResourceManager.GetString("ChooseRemoteHostToDeployWorkieWebAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose remote host to deploy Workie.Web.Admin without config.
        /// </summary>
        internal static string ChooseRemoteHostToDeployWorkieWebAdminWithoutConfig {
            get {
                return ResourceManager.GetString("ChooseRemoteHostToDeployWorkieWebAdminWithoutConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose remote host to install or update packages.
        /// </summary>
        internal static string ChooseRemoteHostToInstallOrUpdatePackages {
            get {
                return ResourceManager.GetString("ChooseRemoteHostToInstallOrUpdatePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose remote host to setup environment.
        /// </summary>
        internal static string ChooseRemoteHostToSetupEnvironment {
            get {
                return ResourceManager.GetString("ChooseRemoteHostToSetupEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose remote host to update Kestrel for Workie.Web.Admin.
        /// </summary>
        internal static string ChooseRemoteHostToUpdateKestrelForWorkieWebAdmin {
            get {
                return ResourceManager.GetString("ChooseRemoteHostToUpdateKestrelForWorkieWebAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Workie.Web.Admin.
        /// </summary>
        internal static string DeployWorkieWebAdmin {
            get {
                return ResourceManager.GetString("DeployWorkieWebAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Workie.Web.Admin without config.
        /// </summary>
        internal static string DeployWorkieWebAdminWithoutConfig {
            get {
                return ResourceManager.GetString("DeployWorkieWebAdminWithoutConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PASSWORD.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter USERNAME.
        /// </summary>
        internal static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install or update packages.
        /// </summary>
        internal static string InstallOrUpdatePackages {
            get {
                return ResourceManager.GetString("InstallOrUpdatePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SSL Enabled.
        /// </summary>
        internal static string IsSslEnabled {
            get {
                return ResourceManager.GetString("IsSslEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msg.
        /// </summary>
        internal static string MessageMin {
            get {
                return ResourceManager.GetString("MessageMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the remote host login credentials.
        /// </summary>
        internal static string PleaseEnterTheRemoteHostLoginCredentials {
            get {
                return ResourceManager.GetString("PleaseEnterTheRemoteHostLoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Workie....
        /// </summary>
        internal static string PreDescription {
            get {
                return ResourceManager.GetString("PreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup environment.
        /// </summary>
        internal static string SetupEnvironment {
            get {
                return ResourceManager.GetString("SetupEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src.
        /// </summary>
        internal static string SourceMin {
            get {
                return ResourceManager.GetString("SourceMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==== STACK TRACE ====.
        /// </summary>
        internal static string StackTraceLoud {
            get {
                return ResourceManager.GetString("StackTraceLoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Kestrel for Workie.Web.Admin.
        /// </summary>
        internal static string UpdateKestrelForWorkieWebAdmin {
            get {
                return ResourceManager.GetString("UpdateKestrelForWorkieWebAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
